version: "3"
services:
  db:
    restart: always
    image: postgres:alpine
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
      - ./volumes/db/log:/var/log/postgresql
    ports:
      - "5432:5432"
    restart: unless-stopped
  app:
    build: 
      context: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app
    depends_on:
      - db
    command: yarn start
